"""Constants for the PySide6 work-bubble helper."""

from __future__ import annotations

WORK_OVERLAY_POINTER_SYNC_MS = 60
WORK_OVERLAY_HOTSPOT_HIT_ALPHA = 8
WORK_OVERLAY_HOTSPOT_HOVER_ALPHA = 0.96
WORK_OVERLAY_WIDTH = 430
WORK_OVERLAY_MARGIN = 16
WORK_OVERLAY_TOP_OFFSET = 56
WORK_OVERLAY_CLOSE_SIZE = 22
WORK_OVERLAY_TEXT_WRAP_WIDTH = WORK_OVERLAY_WIDTH - 28
WORK_OVERLAY_BODY_MAX_LINES = 3
WORK_OVERLAY_CARD_X_PADDING = 10
WORK_OVERLAY_CARD_Y_PADDING = 8
WORK_OVERLAY_CARD_SPACING = 7
WORK_OVERLAY_ESTIMATED_ITEM_HEIGHT = 160
WORK_OVERLAY_COMPLETED_BADGE_SIZE = 168
WORK_OVERLAY_COMPLETED_BADGE_ROW_HEIGHT = 180
WORK_OVERLAY_COMPLETED_BADGE_SPACING = 8
WORK_OVERLAY_COMPLETED_BADGE_ANIMATION_MS = 520
WORK_OVERLAY_STACK_SPACING = 8
WORK_OVERLAY_TRANSITION_CARD_HEIGHT = 110
# Rest-reminder cards carry hint text plus an action button row on top of the
# normal card body, so their slot reserves extra height below the shared
# transition height; cards stacked underneath shift by the same amount.
WORK_OVERLAY_REST_CARD_EXTRA_HEIGHT = 48
WORK_OVERLAY_TRANSITION_SHRINK_MS = 220
WORK_OVERLAY_TRANSITION_PAUSE_MS = 140
WORK_OVERLAY_TRANSITION_MOVE_MS = 280
WORK_OVERLAY_TRANSITION_SHIFT_MS = 240
WORK_OVERLAY_QT_TRANSITION_ANIMATIONS_ENABLED = True
WORK_OVERLAY_RESTORE_FADE_OUT_MS = 200
WORK_OVERLAY_RESTORE_SHIFT_MS = 300
WORK_OVERLAY_RESTORE_FADE_IN_MS = 150
WORK_OVERLAY_RESTORE_DESCEND_MS = 400
WORK_OVERLAY_COMPLETED_ANNIHILATION_MS = 1200
WORK_OVERLAY_COMPLETED_ANNIHILATION_MARGIN = 16
WORK_OVERLAY_TRANSITION_CLEARANCE_PX = (
    WORK_OVERLAY_COMPLETED_BADGE_SIZE + WORK_OVERLAY_COMPLETED_BADGE_SPACING
)
WORK_OVERLAY_SHIMMER_TIMER_MS = 30
WORK_OVERLAY_SHIMMER_STEP_PX = 3.5
WORK_OVERLAY_SHIMMER_BAND_WIDTH_PX = 58
WORK_OVERLAY_SHIMMER_HIGHLIGHT = "#FFFFFF"
WORK_OVERLAY_SHIMMER_PEAK_ALPHA = 245
WORK_OVERLAY_SWITCH_PENDING_SLOW_SECONDS = 3.0
WORK_OVERLAY_SWITCH_PENDING_TIMEOUT_SECONDS = 45.0
WORK_OVERLAY_SWITCH_PENDING_TIMER_MS = 120
WORK_OVERLAY_SWITCH_PENDING_MIN_WIDTH = 150
WORK_OVERLAY_COMPLETED_PENDING_LAUNCH_SECONDS = 0.45
WORK_OVERLAY_COMPLETED_PENDING_FINISH_SECONDS = 0.85
WORK_OVERLAY_EMPTY_GRACE_SECONDS = 0.8
WORK_OVERLAY_STATE_READ_FAILURE_GRACE_SECONDS = 1.2
WORK_OVERLAY_STATE_READ_RETRY_MS = 80
WORK_OVERLAY_HELPER_HEARTBEAT_MS = 5_000
WORK_OVERLAY_ELAPSED_TEXT_TIMER_MS = 1_000
# The only new animation allowed on the bubble: the braille spinner glyph on
# live feed rows. Seconds reuse the 1s elapsed tick; set False for a static
# glyph (or no glyph) with zero extra timer work.
WORK_OVERLAY_FEED_SPINNER_ENABLED = True
WORK_OVERLAY_FEED_SPINNER_TIMER_MS = 120
WORK_OVERLAY_WORKDIR_FOOTER_WIDTH = 170
DEFAULT_WORK_OVERLAY_THEME: dict[str, str] = {
    "surface": "#10161D",
    "panelSurface": "#141B24",
    "panelBorder": "#263241",
    "text": "#DCE7F2",
    "muted": "#8492A6",
    "accent": "#F3D27A",
    "info": "#9CCBFF",
    "warning": "#FFB86B",
    "error": "#FF6B6B",
    "success": "#8FE3A1",
    "requestPanelSurface": "#10161D",
    "requestText": "#B8C6D8",
    "requestMuted": "#5E6A78",
    "progressOverflowBadge": "#7F3E3A",
    "progressOverflowBadgeEdge": "#FF875A",
}

__all__ = [
    "WORK_OVERLAY_POINTER_SYNC_MS",
    "WORK_OVERLAY_HOTSPOT_HIT_ALPHA",
    "WORK_OVERLAY_HOTSPOT_HOVER_ALPHA",
    "WORK_OVERLAY_WIDTH",
    "WORK_OVERLAY_MARGIN",
    "WORK_OVERLAY_TOP_OFFSET",
    "WORK_OVERLAY_CLOSE_SIZE",
    "WORK_OVERLAY_TEXT_WRAP_WIDTH",
    "WORK_OVERLAY_BODY_MAX_LINES",
    "WORK_OVERLAY_CARD_X_PADDING",
    "WORK_OVERLAY_CARD_Y_PADDING",
    "WORK_OVERLAY_CARD_SPACING",
    "WORK_OVERLAY_ESTIMATED_ITEM_HEIGHT",
    "WORK_OVERLAY_COMPLETED_BADGE_SIZE",
    "WORK_OVERLAY_COMPLETED_BADGE_ROW_HEIGHT",
    "WORK_OVERLAY_COMPLETED_BADGE_SPACING",
    "WORK_OVERLAY_COMPLETED_BADGE_ANIMATION_MS",
    "WORK_OVERLAY_STACK_SPACING",
    "WORK_OVERLAY_TRANSITION_CARD_HEIGHT",
    "WORK_OVERLAY_REST_CARD_EXTRA_HEIGHT",
    "WORK_OVERLAY_TRANSITION_SHRINK_MS",
    "WORK_OVERLAY_TRANSITION_PAUSE_MS",
    "WORK_OVERLAY_TRANSITION_MOVE_MS",
    "WORK_OVERLAY_TRANSITION_SHIFT_MS",
    "WORK_OVERLAY_QT_TRANSITION_ANIMATIONS_ENABLED",
    "WORK_OVERLAY_RESTORE_FADE_OUT_MS",
    "WORK_OVERLAY_RESTORE_SHIFT_MS",
    "WORK_OVERLAY_RESTORE_FADE_IN_MS",
    "WORK_OVERLAY_RESTORE_DESCEND_MS",
    "WORK_OVERLAY_COMPLETED_ANNIHILATION_MS",
    "WORK_OVERLAY_COMPLETED_ANNIHILATION_MARGIN",
    "WORK_OVERLAY_TRANSITION_CLEARANCE_PX",
    "WORK_OVERLAY_SHIMMER_TIMER_MS",
    "WORK_OVERLAY_SHIMMER_STEP_PX",
    "WORK_OVERLAY_SHIMMER_BAND_WIDTH_PX",
    "WORK_OVERLAY_SHIMMER_HIGHLIGHT",
    "WORK_OVERLAY_SHIMMER_PEAK_ALPHA",
    "WORK_OVERLAY_SWITCH_PENDING_SLOW_SECONDS",
    "WORK_OVERLAY_SWITCH_PENDING_TIMEOUT_SECONDS",
    "WORK_OVERLAY_SWITCH_PENDING_TIMER_MS",
    "WORK_OVERLAY_SWITCH_PENDING_MIN_WIDTH",
    "WORK_OVERLAY_COMPLETED_PENDING_LAUNCH_SECONDS",
    "WORK_OVERLAY_COMPLETED_PENDING_FINISH_SECONDS",
    "WORK_OVERLAY_EMPTY_GRACE_SECONDS",
    "WORK_OVERLAY_STATE_READ_FAILURE_GRACE_SECONDS",
    "WORK_OVERLAY_STATE_READ_RETRY_MS",
    "WORK_OVERLAY_HELPER_HEARTBEAT_MS",
    "WORK_OVERLAY_ELAPSED_TEXT_TIMER_MS",
    "WORK_OVERLAY_FEED_SPINNER_ENABLED",
    "WORK_OVERLAY_FEED_SPINNER_TIMER_MS",
    "WORK_OVERLAY_WORKDIR_FOOTER_WIDTH",
    "DEFAULT_WORK_OVERLAY_THEME",
]
